### ISSUE TITLE
snails-frame is obscured by other frames.

### ISSUE THREAD

**Issue by ctrl2wei** [manateelazycat/snails#1]
I use emacs in gnome desktop environment，the snails-frame will not be displayed on top
when I use keyboard shortcuts changed emacs frame size.

Maybe should change the code：
https://github.com/manateelazycat/snails/blob/a25e2c867072868dcb1c16e5103a551083cf2d74/snails-core.el#L320-L321

to

``` emacs-lisp

;; Show popup frame.
(make-frame-visible snails-frame)
(select-frame-set-input-focus snails-frame)
```
it works for me.

**Comment by manateelazycat** [comment]
Done in newest version.

Thanks for help
