### ISSUE TITLE
﻿progn: Symbol’s function definition is void: goto-column

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/snails#12]
https://github.com/manateelazycat/snails/blob/df9fa14d97f92948d90ac7db058c080a1f648f16/snails-backend-rg.el#L125

`goto-column` is not defined with the following error:
```
progn: Symbol’s function definition is void: goto-column
```

Another thought: are we able to integrate color-rg into snails? color-rg is very useful and very cool :)

**Comment by manateelazycat** [comment]
补丁修复了 https://github.com/manateelazycat/snails/commit/fe3a06db54950b25de5c0b4f265401e0db8ab90c 
不好意思，自己的私有函数写惯了。

snails-backend-rg 更擅长于临时搜索一下， color-rg 更擅长于全局搜索做重构， color-rg 操控性更好。

当然欢迎说出你的想法，说不定有一些新玩法呢?

**Comment by MatthewZMD** [comment]
Makes sense. 我觉得可以highlight一下rg返回的结果里的关键词

**Comment by manateelazycat** [comment]
那个准备搞了，头两天，不知道为什么不行，过几天再研究一下。
