### ISSUE TITLE
Emacs FROZEN after latest commits

### ISSUE THREAD

**Issue by MatthewZMD** [manateelazycat/snails#14]
With the latest code, when I try to open snails, emacs became **frozen dead** on Lubuntu, I can't even select anything else on the system, the system almost become unusable.
![DeepinScreenshot_select-area_20190724233758](https://user-images.githubusercontent.com/12422335/61844114-4ba02c00-ae6c-11e9-869d-040d011442de.png)
The only way to escape this is to kill the entire Emacs process.
I tried to checkout the previous commit [Refactory code. 92f7c24](https://github.com/manateelazycat/snails/commit/92f7c246c656a4c7dfdd3b771902b377bdbefc76) everything worked great again.

**Comment by manateelazycat** [comment]
Try Newest version, i think has finish.
