### ISSUE TITLE
Snails only show a right half window in vertical screen

### ISSUE THREAD

**Issue by zwpaper** [manateelazycat/snails#16]
![image](https://user-images.githubusercontent.com/3764335/62020627-59500b80-b1f6-11e9-9b6e-be849a7e8923.png)

it works well in my main screen which is horizontal.

BTW, if Emacs is running on macOS full-screen mode, snails will appear in another screen, like this, maybe is caused by posframe?

![2019-07-29 13 04 44](https://user-images.githubusercontent.com/3764335/62023015-80f8a100-b201-11e9-8a20-4e3eb14175f2.gif)

**Comment by manateelazycat** [comment]
Read FAQ

**Comment by zwpaper** [comment]
Sorry for missing FAQ, and it really helps me for fixing the fullscreen problems.

but there still one more question in my post, the first image, it is not caused by full-screen, I have tested it on a normal window.

my screen is vertical, and maybe the contents of snails are too long to show, as a result, I can only see the right half of the snails window.

And it works perfectly on my horizontal screen.
