### ISSUE TITLE
snails doesn't show anything only with high CPU usage

### ISSUE THREAD

**Issue by stardiviner** [manateelazycat/snails#26]
I install snails:

```elisp
(leaf snails ; A modern, easy-to-expand fuzzy search framework.
  :require t
  :el-get (snails :url "https://github.com/manateelazycat/snails.git" :features snails))
```
And using Emacs version (latest commit from master branch source code):
```
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-08
```

When I use configured Emacs open command `snails`.
It shows a new frame but I can't input, only saw the CPU using high usage.

When I use a minimal init Emacs to open command `snails`.
Snails frame can input, but still shows nothing. As this screenshot.

![image](https://user-images.githubusercontent.com/378699/62744745-8fa14c80-ba7a-11e9-9fb3-2d359bfb629d.png)

**Comment by manateelazycat** [comment]
先用 emacs -Q 做一个对比测试

**Comment by stardiviner** [comment]
I tested with `emacs -Q`. Still same. And I toke a screenshot:

![image](https://user-images.githubusercontent.com/378699/62914370-acaf8580-bdc2-11e9-8f69-5e4ec187a902.png)

**Comment by manateelazycat** [comment]
建议自定义一下 snails-default-backends 变量，看看是哪个后端引起的？

**Comment by stardiviner** [comment]
When I use: `(snails '(snails-backend-buffer))`, Same for `(snails '(snails-backend-recentf))`.

I got this:

```
[nil 23891 23273 202259 nil #[0 "À\0r	qÃ )\0Är
qc)Å!ÅÄ!" [nil snails-start-buffer snails-input-buffer snails-pointer-string "" snails-search] 3] nil nil 14000]
[nil 23891 23306 328813 nil #[0 "À\0r	qÃ )\0Är
qc)Å!ÅÄ!" [nil snails-start-buffer snails-input-buffer snails-pointer-string "" snails-search] 3] nil nil 627000]
```

**Comment by manateelazycat** [comment]
无法重现问题和找到原因，如果有准确原因欢迎重新提交 issue
