### ISSUE TITLE
当设置 snail-fuz-library-load-status 为 check 时，无法使用 fuz 库

### ISSUE THREAD

**Issue by shanyouli** [manateelazycat/snails#27]
1. 在关于 [snails-fuz-library-load-status](https://github.com/manateelazycat/snails/blob/6a86abbc4fdd400c4252ff17355534ec39096427/snails-core.el#L258) 变量的文档说明中使用的 `check` 和 `uncheck` ， 如下图所示
![AwesomeScreenshot-github-manateelazycat-snails-blob-6a86abbc4fdd400c4252ff17355534ec39096427-snails-core el-2019-08-10_12_00](https://user-images.githubusercontent.com/48723272/62792472-f4ec5080-bb01-11e9-801c-42c268da2217.png)
2. 在函数 [snails-fuz-library-load-p](https://github.com/manateelazycat/snails/blob/6a86abbc4fdd400c4252ff17355534ec39096427/snails-core.el#L1068) 对 snails-fuz-library-load-status 判断中不包含 check，而是使用 load 取代了，如图
![2019-08-10_12_08](https://user-images.githubusercontent.com/48723272/62792950-fa966600-bb02-11e9-83b6-63bb0a33c64b.png)

**Comment by shanyouli** [comment]
这是关于我对 snails 的配置
```
(require 'fuz)
(require 'snails)
(setq snails-fuz-library-load-status "check") ; 若要是 fuz 库在 snails 中生效，此处的 check 应该改为 `load` 
```
PS： 请修正对 snails-fuz-library-load-status 文档的描述

**Comment by manateelazycat** [comment]
文档有点问题，但是你只要require fuz就可以了，不需要设置这个内部变量的值，这个变量是内部用的，不需要去设置

**Comment by shanyouli** [comment]
问题是当我 require fuz 后，第一次运行 snails 时， 会因为执行  snails-fuz-library-load-p  中的 （load-library "fuz"）会再一次 load fuz 并生成一个 " *load*" 的 buffer。这才是我为什么要设置 snails-fuz-library-load-status 为 load 的原因

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/snails/commit/394a7db4873dfa36f6a940ee3bf5e554c9b78b78
