### ISSUE TITLE
performance test `xterm-color` for highlights

### ISSUE THREAD

**Issue by slippycheeze** [manateelazycat/snails#31]
In my own testing, on macOS, https://melpa.org/#/xterm-color provides significantly better performance when doing ANSI/VT* color sequence processing.  I don't have the resources or systems to test more broadly, so can't vouch for performance elsewhere, but I'd encourage you to test it yourself and determine if it meets your performance goals.

**Comment by manateelazycat** [comment]
Thanks for info.

I will check later, thanks
