### ISSUE TITLE
No popup on i3wm

### ISSUE THREAD

**Issue by Compro-Prasad** [manateelazycat/snails#32]
![ezgif com-resize](https://user-images.githubusercontent.com/11143962/66271625-e90cd880-e87d-11e9-83ce-c0003bf2b6ec.gif)

**Comment by manateelazycat** [comment]
I don't know how to fix this issue since i even don't use i3wm

**Comment by sxqsfun** [comment]
i try add i3 config:
```
for_window [title="snails"] floating enable
```
it's work.

**Comment by Compro-Prasad** [comment]
Thanks for the config. But it doesn't get autoselected as my cursor moves to the topleft corner.
