### ISSUE TITLE
使用 everything 搜不到东西

### ISSUE THREAD

**Issue by loyalpartner** [manateelazycat/snails#33]
![snails-error](https://user-images.githubusercontent.com/1442249/67137062-0b312e00-f262-11e9-8384-7f80b27ef0be.gif)
es 命令已经放到 path 路径了
查了下 snails-backends 的值
(snails-backend-projectile snails-backend-fd snails-backend-mdfind snails-backend-everything)
不知道是不是我使用方法不对，

**Comment by manateelazycat** [comment]
@smallzhan 来回答吧

**Comment by loyalpartner** [comment]
今天又试了一下，发现是能搜的，但是有2秒左右的延迟，我误以为没有搜到结果
