### ISSUE TITLE
require包后选项框是空的

### ISSUE THREAD

**Issue by liguangsheng** [manateelazycat/snails#5]
```
(add-to-list 'load-path (concat emacs-site-lisp-dir "snails"))
(require 'snails)
```

我是这样加载包的，加载完以后M-x snails，没有可搜索的项
![image](https://user-images.githubusercontent.com/8074650/61677786-6753e700-ad33-11e9-90af-bddd305776b8.png)

**Comment by liguangsheng** [comment]
MacOS Emacs 26.1

**Comment by liguangsheng** [comment]
原因是用了straight加载，换成load-path就好了

**Comment by ztlevi** [comment]
为啥不支持用straight加载呢？
