### ISSUE TITLE
关于 snails-backend-rg 的两个问题

### ISSUE THREAD

**Issue by Leoongithub** [manateelazycat/snails#71]
1. 使用`snails-backend-rg`时，会用到一个`snails-project-root-dir`的变量，但是默认情况下这个变量为nil，导致搜索无法进行，这个变量应该如何设置呢？
2. 代码中的`first`、`second`（以及最近一次commit的`string-replace`）都显示`void-function`，是缺少什么package或者是emacs需要更新吗（目前使用的是27.2）？

**Comment by manateelazycat** [comment]
1. snails-core.el 中 snails 启动的时候会设置 snails-project-root-dir
2. first/second 在 cl.el 中， string-replace 在 subr.el 中，你可以通过 C-h f 自己来找到函数的定义

**Comment by Leoongithub** [comment]
感谢回复，仍然有问题未解决
1. `snails-project-root-dir`的初始值来源于`(project-current)`，我对这个包不太熟悉，它似乎需要安装git，但是我没有，所以`(project-current)`返回的是`nil`，能否在这种情况下以当前文件所在目录进行搜索呢？
2. `snails-backend-rg`的`@`语法也没有生效，直接执行`(snails '(snails-backend-rg) "keyword@d:\\project")`的结果是`nil`，但我通过调试发现直到[build-command](https://github.com/manateelazycat/snails/blob/93a8a7a792e50876a3f4117744d9d864171e0972/snails-backend-rg.el#L113)这一步都没有问题，生成的指令拿到eshell里运行也可以正常搜索，我应该如何调试是哪一步出的问题？

**Comment by manateelazycat** [comment]
project-current 就是内置的 project.el 包带入的，当前目录会受打开文件的影响，没有当前目录方便。

**Comment by manateelazycat** [comment]
@ 语法我测试了，可以工作
