### ISSUE TITLE
使用 add-function 处理 focus-in 和 focus-out 事件

### ISSUE THREAD

**Issue by mkvoya** [manateelazycat/snails#75]
https://github.com/manateelazycat/snails/blob/5899464de09cdf8c8e74dd428d54523b1f2433ce/snails-core.el#L813

根据 [这个 stackexchange 帖子](https://emacs.stackexchange.com/a/60971/30542) 的内容，`after-focus-change-function` 应该使用 `add-function`，现在使用 `add-hook` 在 focus-in 和 focus-out 的时候会报错：

```
handle-focus-out: Invalid function: (snails-quit #[128 "��\"��\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
handle-focus-in: Invalid function: (snails-quit #[128 "��\"��\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
handle-focus-out: Invalid function: (snails-quit #[128 "��\"��\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
```

改成下面这样就没报错

```elisp
        (add-function :after after-focus-change-function 'snails-quit)))
```

另外我发现其他几处 xxx-functions 也是使用了 `add-hook`，由于对 snails 不是很熟悉，不知是否也需要修改。

**Comment by manateelazycat** [comment]
> https://github.com/manateelazycat/snails/blob/5899464de09cdf8c8e74dd428d54523b1f2433ce/snails-core.el#L813
> 
> 根据 [这个 stackexchange 帖子](https://emacs.stackexchange.com/a/60971/30542) 的内容，`after-focus-change-function` 应该使用 `add-function`，现在使用 `add-hook` 在 focus-in 和 focus-out 的时候会报错：
> 
> ```
> handle-focus-out: Invalid function: (snails-quit #[128 "���\"���\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
> handle-focus-in: Invalid function: (snails-quit #[128 "���\"���\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
> handle-focus-out: Invalid function: (snails-quit #[128 "���\"���\"��" [apply posframe--redirect-posframe-focus ignore nil] 5 nil nil])
> ```
> 
> 改成下面这样就没报错
> 
> ```emacs-lisp
>         (add-function :after after-focus-change-function 'snails-quit)))
> ```
> 
> 另外我发现其他几处 xxx-functions 也是使用了 `add-hook`，由于对 snails 不是很熟悉，不知是否也需要修改。

直接来个PR？ 我直接按照你的要求合并了吧，最近忙，没时间玩Elisp. :(
