### ISSUE TITLE
Snails启动时与任何需要改变窗口布局的函数冲突

### ISSUE THREAD

**Issue by cireu** [manateelazycat/snails#8]
Snails可以与Helm嵌套

![图片](https://user-images.githubusercontent.com/18224684/61705953-7d849600-ad79-11e9-9faa-dc373bf8e761.png)

Snail里执行`describe-key

![图片](https://user-images.githubusercontent.com/18224684/61705987-95f4b080-ad79-11e9-824d-b1e1debcc213.png)

导致无法用`C-g`退出，只能用`C-x C-c`杀掉frame

**Comment by manateelazycat** [comment]
为什么要混着用？

**Comment by cireu** [comment]
且不说叠加helm吧，describe-key还是挺常用的。

**Comment by manateelazycat** [comment]
其实就是minibuffer激活的时候退出snaila，你是这个意思吗？

**Comment by cireu** [comment]
这样倒也可行

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/snails/commit/0e2362894bbdebe28f700c907eca95daa361947b fixed
