### ISSUE TITLE
emacs "29.0.50" M-x snails执行报错

### ISSUE THREAD

**Issue by lynnux** [manateelazycat/snails#81]
报的
```
if: Wrong type argument: stringp, (Git "~/.emacs.d/")
```
查看snails定义，在
```
(setq snails-project-root-dir
          (let ((project (project-current)))
            (when project
              (if (version< "27.0" emacs-version)
                  (expand-file-name (cdr project))
                (expand-file-name (car (last project))))
              )))
```
执行就报错了，`(project-current)`返回的是`(vc Git "~/.emacs.d/")`

**Comment by lynnux** [comment]
我去，这个(version< "27.0" emacs-version)居然返回t，

**Comment by lynnux** [comment]
随便修改了让上面通过，然后又报错`Invalid frame name--not a string or nil`，定位到`snails-create-popup-window`
```
(unless (and
             snails-frame
             (frame-visible-p snails-frame))
      (setq snails-frame
            (make-frame
             '((name . snails-frame-name)        -------- 只有把snails-frame-name改为"emacs-snails"才行
               (parent-frame . snails-init-frame)
               (skip-taskbar . t)
               (minibuffer . nil)
               (visibility . nil)
               (internal-border-width . 0)
               (left-fringe . 0)
               (right-fringe . 0)
               (vertical-scroll-bars . nil)
               (horizontal-scroll-bars . nil)
               (undecorated . t)
               (unsplittable . t)
               (tool-bar-lines . 0)
               (menu-bar-lines . 0)
               (tab-bar-lines . 0)
               ))))
```
上面通过后，补全也有问题，输入两个就不行了，见gif:
![录像13_转](https://user-images.githubusercontent.com/367894/167330820-c9334f34-1848-4135-8514-291909996afa.gif)
查看*Message*提示：`Symbol’s function definition is void: eaf-is-valid-web-url`  ，搜索了snails里确实有这个调用，但我没有装eaf。。

**Comment by lynnux** [comment]
另外我还没装fuz.el，现在搜索current buffer和rg好像都要输入至少4个字符才启动搜索，看了下rg的代码好像没有变量可以定制这个？ (fd是2个就可以了)

**Comment by manateelazycat** [comment]
> 另外我还没装fuz.el，现在搜索current buffer和rg好像都要输入至少4个字符才启动搜索，看了下rg的代码好像没有变量可以定制这个？ (fd是2个就可以了)

https://github.com/manateelazycat/snails/blob/fbfebf7b42ef5fe3443fe4e4439ae6c0cdcd39b3/snails-backend-rg.el#L98

目前还没有变量，可以帮忙写一个 PR 增加一个变量，谢谢。 ;)

**Comment by lynnux** [comment]
默认搜索不以空格分词吗，如下gif，s c不能匹配snails-core.el：
![录像16_转](https://user-images.githubusercontent.com/367894/167541200-256c95f2-f59c-4e9c-a5e7-977014cf2971.gif)

**Comment by manateelazycat** [comment]
安装 https://github.com/rustify-emacs/fuz.el
